import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { Basic, Geist_Mono } from 'next/font/google';
import '@fontsource/alyamama';
import '../globals.css';
import Navbar from '@/components/Navbar';

const basic = Basic({
  weight: '400',
  variable: '--font-basic',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Almoatamer',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  const dir = locale === 'ar' ? 'rtl' : 'ltr';

  const fontStyle = {
    '--font-primary': locale === 'ar' ? '"Alyamama", sans-serif' : 'var(--font-basic)',
  } as React.CSSProperties;

  return (
    <html lang={locale} dir={dir} className={`${basic.variable} ${geistMono.variable} h-full antialiased`} style={fontStyle}>
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
